Cocktail details
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #10
Opened 2021-11-03 14:36 UTC by HeloiseFerla

2021-11-03 14:56 UTC, PierreGoe approved these changes, later dismissed

2021-11-03 14:56 UTC, PierreGoe commented on src/components/CocktailDetail/style.css
> +}
maybe use Grid css in this case is better but it's good

2021-11-04 09:23 UTC, Hacene010 requested changes
Take a look on the comment and fix the error plz

2021-11-04 09:23 UTC, Hacene010 commented on src/components/CocktailDetail/index.jsx
> +  const [cocktail, setCocktail] = useState([]);
If your state is an array it should be plural

2021-11-04 10:47 UTC, PierreGoe approved these changes

2021-11-04 10:48 UTC, Hacene010 approved these changes
ok for me ; )

2021-11-04 10:51 UTC, merged