Footer design
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #26
Opened 2021-11-10 10:04 UTC by PierreGoe

2021-11-10 10:11 UTC, LuigiMenez approved these changes, later dismissed
It's good for me

2021-11-10 10:18 UTC, Hacene010 requested changes
Seen some evils plz correct it

2021-11-10 10:18 UTC, Hacene010 commented on src/components/Footer/index.jsx
> +          <div className="member-info">
Use camelCasse for all classNames to be coherent :)

2021-11-10 10:18 UTC, Hacene010 commented on src/components/Footer/index.jsx
> +            <div className="social-links">
same here

2021-11-10 10:18 UTC, Hacene010 commented on src/components/Footer/index.jsx
> +          <div className="member-info">
same here

2021-11-10 10:18 UTC, Hacene010 commented on src/components/Footer/index.jsx
> +            <div className="social-links">
same

2021-11-10 10:18 UTC, Hacene010 commented on src/components/Footer/index.jsx
> +          <div className="member-info">
same

2021-11-10 10:18 UTC, Hacene010 commented on src/components/Footer/index.jsx
> +            <div className="social-links">
same

2021-11-10 14:59 UTC, LoicBrassart commented
No SM validation

2021-11-10 15:18 UTC, LuigiMenez submitted a review, later dismissed
It's good.

2021-11-15 09:00 UTC, Hacene010 submitted a review, later dismissed
Ok for me

2021-11-15 09:45 UTC, LuigiMenez approved these changes
Fix conflict, linear-gradient in CocktaiCard style.css

2021-11-15 11:22 UTC, Hacene010 approved these changes
ok

2021-11-15 12:17 UTC, merged