Carousel
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #27
Opened 2021-11-10 10:06 UTC by PierreGoe

2021-11-10 10:25 UTC, LuigiMenez approved these changes, later dismissed
It's good for me.

2021-11-10 10:55 UTC, LoicBrassart requested changes
A few Evils to fix

2021-11-10 10:55 UTC, LoicBrassart commented on src/components/Carousel/index.jsx
> +import { useState } from 'react/cjs/react.development';
... Nope ?

2021-11-10 10:55 UTC, LoicBrassart commented on src/components/Carousel/index.jsx
> +  const nextSlice = () => {
nextSli**d**e ? prevSli**d**e ?

2021-11-10 11:06 UTC, PierreGoe commented on src/components/Carousel/index.jsx
> +import { useState } from 'react/cjs/react.development';
done

2021-11-10 11:07 UTC, PierreGoe commented on src/components/Carousel/index.jsx
> +  const nextSlice = () => {
done

2021-11-10 15:00 UTC, LoicBrassart commented
No SM validation

2021-11-10 15:15 UTC, LuigiMenez submitted a review, later dismissed
Good for me

2021-11-15 13:10 UTC, LoicBrassart commented
No SM validation

2021-11-15 13:12 UTC, LuigiMenez approved these changes
Ok for me.

2021-11-15 16:39 UTC, LoicBrassart approved these changes
No more Evil

2021-11-15 16:39 UTC, LoicBrassart commented on src/components/CocktailDetail/index.jsx
(Almost sure that Prettier/ESLint forbid you having 2 successive empty lines... I iz suspicious, have you set it up ?)

2021-11-15 17:41 UTC, merged