Update readme.md
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #59
Opened 2021-11-17 15:27 UTC by Morel-Victor

2021-11-17 15:29 UTC, LuigiMenez approved these changes, later dismissed

2021-11-18 09:23 UTC, LoicBrassart requested changes
Minor typos

2021-11-18 09:23 UTC, LoicBrassart commented on README.md
> +He references more than 700 cocktails.
"It" :p

2021-11-18 09:23 UTC, LoicBrassart commented on README.md
> +Each one has his recipe to make the best cocktails.
it's recipe

2021-11-18 09:30 UTC, PierreGoe commented on README.md
> +He references more than 700 cocktails.
solve

2021-11-18 09:30 UTC, PierreGoe commented on README.md
> +Each one has his recipe to make the best cocktails.
solve

2021-11-18 09:37 UTC, LuigiMenez approved these changes
Good.

2021-11-18 09:43 UTC, LoicBrassart approved these changes
Better ;-)

2021-11-18 09:57 UTC, merged