Create Router
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #6
Opened 2021-10-29 13:00 UTC by PierreGoe

2021-10-29 13:21 UTC, HeloiseFerla submitted a review, later dismissed
To be modified when we will develop the cocktailDetails

2021-11-02 11:19 UTC, LoicBrassart requested changes
Minor Evils to fix, see comments

2021-11-02 11:19 UTC, LoicBrassart commented on src/App.jsx
> +      {' '}
Useless

2021-11-02 11:19 UTC, LoicBrassart commented on src/App.jsx
> +      <>
Useless Fragment (artifact from before-router ?)

2021-11-02 11:19 UTC, LoicBrassart commented on src/index.jsx
> +
... Why ?

2021-11-02 19:33 UTC, Morel-Victor commented on src/App.jsx
> +      {' '}
Useless line resolved

2021-11-02 19:35 UTC, Morel-Victor commented on src/App.jsx
> +      <>
Useless fragment removed

2021-11-02 19:36 UTC, Morel-Victor commented on src/index.jsx
> +
Useless white space removed

2021-11-03 08:35 UTC, HeloiseFerla submitted a review, later dismissed
ok

2021-11-03 10:35 UTC, LoicBrassart approved these changes, later dismissed
No more Evils ! \o/

2021-11-03 11:13 UTC, HeloiseFerla approved these changes
ok

2021-11-03 11:24 UTC, Hacene010 approved these changes
It's ok for me ;)

2021-11-03 11:25 UTC, merged