Add heart to CocktailDetail
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #66
Opened 2021-11-18 19:38 UTC by HeloiseFerla

2021-11-18 20:00 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2021-11-19 09:23 UTC, Hacene010 requested changes
I'm not sure your SM reviewed this PR ???

2021-11-19 09:23 UTC, Hacene010 commented on src/components/CocktailCard/style.css
> +    /* ou width : 500px;*/
Dead code.

2021-11-19 09:39 UTC, LoicBrassart commented
No SM validation

2021-11-19 09:39 UTC, LuigiMenez approved these changes
Ok for me.

2021-11-19 10:16 UTC, Hacene010 approved these changes

2021-11-19 10:41 UTC, merged