Create Searchbar
WildCodeSchool/p2-g4-sept21-lille-react-cocktails pull request #8
Opened 2021-10-29 15:34 UTC by PierreGoe

2021-10-30 13:13 UTC, HeloiseFerla submitted a review, later dismissed
ok

2021-11-02 11:41 UTC, LoicBrassart requested changes
Please fix !

2021-11-02 11:41 UTC, LoicBrassart commented on src/App.jsx
> +
?

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/Header/index.jsx
> +        ) : null}
Make it easier to read:
```
displaySearch &&
          <SearchBar
            searchBarInputUser={searchBarInputUser}
            setSearchBarInputUser={setSearchBarInputUser}
            statsSearchBar={statsSearchBar}
            setStatsSearchBar={setStatsSearchBar}
          />
```

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/Header/index.jsx
> +  setSearchBarInputUser: PropTypes.string,
`function`

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/Header/index.jsx
> +  setStatsSearchBar: PropTypes.bool,
`function`

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/SearchBar/index.jsx
> +
?

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/SearchBar/index.jsx
> +            id="maRecherche"
English plz !

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/SearchBar/index.jsx
> +            name="q"
Bad variable name : mySearch ?

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/SearchBar/index.jsx
> +  setSearchBarInputUser: PropTypes.string,
`function`

2021-11-02 11:41 UTC, LoicBrassart commented on src/components/SearchBar/index.jsx
> +  setStatsSearchBar: PropTypes.bool,
`function`

2021-11-02 21:14 UTC, Morel-Victor commented on src/App.jsx
> +
white line is removed

2021-11-02 21:15 UTC, Morel-Victor commented on src/components/Header/index.jsx
> +        ) : null}
Done !

2021-11-02 21:15 UTC, Morel-Victor commented on src/components/Header/index.jsx
> +  setSearchBarInputUser: PropTypes.string,
PropsType modify

2021-11-02 21:15 UTC, Morel-Victor commented on src/components/Header/index.jsx
> +  setStatsSearchBar: PropTypes.bool,
PropsType modify

2021-11-02 21:16 UTC, Morel-Victor commented on src/components/SearchBar/index.jsx
> +
white line are revoded

2021-11-02 21:16 UTC, Morel-Victor commented on src/components/SearchBar/index.jsx
> +            id="maRecherche"
variable name is change

2021-11-02 21:16 UTC, Morel-Victor commented on src/components/SearchBar/index.jsx
> +            name="q"
variable name is change

2021-11-02 21:19 UTC, Morel-Victor commented on src/components/SearchBar/index.jsx
> +  setSearchBarInputUser: PropTypes.string,
PropsType modify

2021-11-02 21:19 UTC, Morel-Victor commented on src/components/SearchBar/index.jsx
> +  setStatsSearchBar: PropTypes.bool,
PropsType modify

2021-11-03 08:46 UTC, HeloiseFerla approved these changes
ok

2021-11-03 10:42 UTC, LoicBrassart approved these changes
No more Evils

2021-11-03 11:06 UTC, merged